apiVersion: apps/v1

kind: Deployment

metadata:
  #Oriignal name of the Deployemnt
  name: kubetest-deployment
  

spec:
  selector: #app it is refrencing  
    matchLabels:
     app: kubetest-pod
  replicas: 1

  template: #template for the pods.  # This is the pod section
     metadata: 
        labels: 
            app: kubetest-pod
            creation_method: manual
            env: Production

     spec:  #This is the container section
      containers:

       - name: kubetest-app
                
         image: jokoyoski/kubetest:v3

         env: 
           - name: joko__name
             value : adeola
           - name : joko__age  
             value: '34'
         livenessProbe:
            httpGet:
               path: /values
               port: 80
               httpHeaders:
               - name: Custom-Header
                 value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3
         ports:
         - containerPort: 80
           protocol: TCP
         resources:
           limits:
             cpu: 500m
             memory: 1Gi
           requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
 name: kubetest-service
spec:
  ports:
  - port: 80  
    targetPort: 80
    protocol: TCP


  selector: 
    app: kubetest-pod    #pod it is targetiing
  
  type: ClusterIP  